const {chromium}=require(process.env.PATRONUS_PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs'); const path=require('node:path'); const output=process.env.PATRONUS_UI_OUTPUT || require('node:os').tmpdir(); const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PATRONUS_BROWSER_EXECUTABLE ? {executablePath:process.env.PATRONUS_BROWSER_EXECUTABLE} : {})});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}}); const messages=[]; const html=JSON.parse(fs.readFileSync(path.join(__dirname,'../server/mcp_home.ts'),'utf8').split('export const homeHtml = ')[1].trim().replace(/;$/, ''));
 await page.route('http://preview.test/**', async route=>route.fulfill({contentType:'text/html',body:route.request().url().endsWith('/home')?html:`<html><body style="margin:0"><iframe src="/home" style="width:100vw;height:100vh;border:0"></iframe><script>window.addEventListener('message',event=>{const m=event.data;window.capture(m);if(!m.id)return;const result=m.method==='tools/call'?{structuredContent:{status:'completed',safety_status:'safe'}}:{};event.source.postMessage({jsonrpc:'2.0',id:m.id,result},'*')})</script></body></html>`}));
 await page.exposeFunction('capture', m=>messages.push(m));await page.goto('http://preview.test/');const ui=page.frameLocator('iframe'); await page.screenshot({path:path.join(output,'patronus-ui-debug.png')});await ui.getByRole('heading',{name:/Your context/}).waitFor();
 assert.equal(messages.filter(m=>m.method==='tools/call').length,0); await page.screenshot({path:path.join(output,'patronus-home-new.png'),fullPage:true});
 await ui.getByRole('button',{name:'Set up Patronus'}).click();await ui.getByRole('heading',{name:'Your Patronus setup.'}).waitFor();await page.screenshot({path:path.join(output,'patronus-setup-new.png')});await ui.locator('#setup-dialog [data-close]').click();
 await ui.locator('[data-scan="url"]').click();await ui.locator('#scan-url').fill('https://example.com/');await ui.locator('#scan-submit').click();await ui.locator('#scan-status').filter({hasText:'Scan response received.'}).waitFor();assert(messages.some(m=>m.method==='tools/call'&&m.params.name==='scan_url'&&m.params.arguments.url==='https://example.com/'));await ui.locator('#scan-dialog [data-close]').click();
 await ui.locator('[data-scan="text"]').click();await ui.locator('#scan-text').fill('Explicit user selected content');await ui.locator('#scan-submit').click();await ui.locator('#scan-status').filter({hasText:'Scan response received.'}).waitFor();assert(messages.some(m=>m.method==='tools/call'&&m.params.name==='submit_scan'));await ui.locator('#scan-dialog [data-close]').click();
 await ui.locator('[data-scan="file"]').click();await ui.locator('[data-kind="text"]').click();await ui.locator('#text-field').waitFor({state:'visible'});await ui.locator('[data-kind="file"]').click();assert.equal(await ui.locator('[data-kind="file"]').getAttribute('aria-pressed'),'true');await ui.locator('#scan-file').setInputFiles({name:'example.txt',mimeType:'text/plain',buffer:Buffer.from('Selected document')});await ui.locator('#scan-submit').click();await ui.locator('#scan-status').filter({hasText:'Scan response received.'}).waitFor();assert(messages.some(m=>m.method==='tools/call'&&m.params.name==='scan_file'&&Buffer.from(m.params.arguments.data_base64,'base64').toString()==='Selected document'));await page.screenshot({path:path.join(output,'patronus-scan-polished.png')});await ui.locator('#scan-dialog [data-close]').click();
 await ui.locator('[data-scan="server"]').click();await ui.locator('#scan-url').fill('https://example.com/mcp');await ui.locator('#scan-submit').click();await ui.locator('#scan-status').filter({hasText:'Scan response received.'}).waitFor();assert(messages.some(m=>m.method==='tools/call'&&m.params.name==='scan_server'));await ui.locator('#scan-dialog [data-close]').click();
 await ui.locator('[data-action="repo"]').click();for(let i=0;i<20&&!messages.some(m=>m.method==='ui/message');i++)await new Promise(r=>setTimeout(r,20));assert(messages.some(m=>m.method==='ui/message'&&m.params.role==='user'));await ui.locator('[data-open="https://control.patronus.studio"]').first().click();for(let i=0;i<20&&!messages.some(m=>m.method==='ui/open-link');i++)await new Promise(r=>setTimeout(r,20));assert(messages.some(m=>m.method==='ui/open-link'));
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'patronus-home-new-mobile.png')});const overflow=await page.frames()[1].evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);
 console.log('PASS: no scan on open, setup dialog, URL/text/file/MCP direct actions, user message, dashboard link, mobile layout');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
