import { bundle } from '../native/scripts/builder.mjs'
import { mkdtemp, writeFile, rm, mkdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { pathToFileURL, fileURLToPath } from 'node:url'

const directory = await mkdtemp(join(tmpdir(), 'patronus-api-home-'))
try {
  const entry = fileURLToPath(new URL('../native/src/ui.ts', import.meta.url))
  const modulePath = join(directory, 'home.mjs')
  await writeFile(modulePath, await bundle(entry, modulePath))
  const { apiHomeHtml } = await import(pathToFileURL(modulePath).href)
  const output = new URL('./server/', import.meta.url)
  await mkdir(output, { recursive: true })
  await writeFile(new URL('mcp_home.ts', output), '// Generated by plugins/codex-api/build-home.mjs from the shared Patronus dashboard design.\nexport const homeUri = "ui://patronus/home";\nexport const homeHtml = ' + JSON.stringify(apiHomeHtml) + ';\n')
  await writeFile(join(tmpdir(), 'patronus-api-home.html'), apiHomeHtml)
  console.log('Prepared hosted MCP home source and HTML preview.')
} finally { await rm(directory, { recursive: true, force: true }) }
