#!/usr/bin/env node
// n8n verifies only self-contained community nodes built with @n8n/node-cli, so the n8n
// package embeds a copy of the shared Guard release policy in n8n/nodes/Patronus/lib.
// The canonical source stays in shared/guard-policy.ts;
// this script regenerates the copy and `--check` fails when it is out of date.
import { readFile, writeFile, mkdir } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const target = new URL('n8n/nodes/Patronus/lib/', root);
const header = '// Generated by plugins/automations/scripts/sync-n8n-lib.mjs from the canonical sources. Do not edit.\n';
const sources = {
  'policy.ts': new URL('shared/guard-policy.ts', root),
};

function rewrite(text) {
  return text
    .replaceAll("'../../../sdk/typescript/src/index.js'", "'./sdk'")
    .replaceAll("'./guard.js'", "'./guard'");
}

const check = process.argv.includes('--check');
let stale = [];
await mkdir(target, { recursive: true });
for (const [name, source] of Object.entries(sources)) {
  const expected = header + rewrite(await readFile(source, 'utf8'));
  const file = new URL(name, target);
  const current = await readFile(file, 'utf8').catch(() => null);
  if (current === expected) continue;
  if (check) stale.push(name);
  else await writeFile(file, expected);
}
if (stale.length) {
  console.error(`n8n/nodes/Patronus/lib is out of date (${stale.join(', ')}). Run: node plugins/automations/scripts/sync-n8n-lib.mjs`);
  process.exitCode = 1;
}
